version: '3.3'

services:
  jenkins:
    image: jenkins-docker
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - traefik-jenkins
    ports:
      - 8080
      - 50000
    deploy:
      placement:
        constraints:
          - node.labels.jenkins.jenkins_home == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-jenkins
        - traefik.constraint-label=traefik-jenkins
        - traefik.http.routers.jenkins-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.jenkins-http.entrypoints=http
        - traefik.http.routers.jenkins-http.middlewares=https-redirect
        - traefik.http.routers.jenkins-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.jenkins-https.entrypoints=https
        - traefik.http.routers.jenkins-https.tls=true
        - traefik.http.routers.jenkins-https.tls.certresolver=le
        - traefik.http.services.jenkins.loadbalancer.server.port=8080

networks:
  traefik-jenkins:
    external: true

volumes:
  jenkins_home: