# Define the number of nodes
NUM_NODE = 1

Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-12.4"
    config.vm.box_version = "202401.31.0"
    config.vm.box_check_update = false
    (1..NUM_NODE).each do |i|
        config.vm.define "vm0#{i}" do |node|
          node.vm.provider :vmware_desktop do |vmware|
            vmware.cpus = 2
            vmware.memory = 4096
            vmware.gui = true
            vmware.vmx["ethernet0.virtualdev"] = "vmxnet3"
          end
          node.vm.hostname = "vm0#{i}"
          node.vm.network "forwarded_port", guest: 22, host: "#{2720 + i}"
          end
      end
  end