Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-12.4"
    config.vm.box_version = "202401.31.0"
    config.vm.box_check_update = false
    config.vm.define "debian-12.4-jenkins-lab"
    
    config.vm.provider "vmware_desktop" do |vmware|
      vmware.cpus = 2
      vmware.memory = 2048
      vmware.gui = true
      vmware.vmx["ethernet0.virtualdev"] = "vmxnet3"
    end
    # config.vm.provision "shell" do |s|
    #     s.path = "./scripts/_common/firewall.sh"
    # end
    config.vm.provision :shell, privileged: true, path: "./scripts/debian/optimizer.sh"
    config.vm.provision :shell, privileged: true, path: "./scripts/devops/docker.sh"
end