Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-12.4"
    config.vm.box_version = "202401.31.0"
    config.vm.box_check_update = false
    config.vm.synced_folder ".", "/mnt/host_machine", create: true
    
    config.vm.provider :virtualbox do |vb|
      vb.name = "debian-12.4-lab"
      vb.memory = "4069"
      vb.cpus = "2"
    end
    # config.vm.provision "shell" do |s|
    #     s.path = "./scripts/_common/firewall.sh"
    # end
end