apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins
  namespace: jenkins
spec:
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: letsencrypt-production
  dnsNames:
  - jenkins.k8s.com